### PR TITLE
Allow loading of reports generated by Artillery 2.x.x

### PR DESCRIPTION
**Pull request by WillGibson**

### CODE REVIEW

**Review by cfryerdev — APPROVED** [review]

**Comment by WillGibson** [comment]
Hi @cfryerdev I don't think this is ready to merge, it only gets some of the bits working. Unless you're happy with an incremental approach to getting it working?

**Comment by cfryerdev** [comment]
Either is fine, as the changes are pretty safe. I appreciate the contribution.

**Comment by cfryerdev** [comment]
Once finished, I will make sure these go into the 2.0.0-slim release as well.

**Comment by WillGibson** [comment]
If I got it right, would I expect the output from these two reports to be the same?

https://github.com/artilleryio/report-viewer/tree/main/samples

**Comment by cfryerdev** [comment]
@WillGibson Would you mind sending me your report file and id be happy to work through and test this before merge. Happy to help however I can.

**Comment by WillGibson** [comment]
Ah, I have had no time to look at this. I'll see if I can get a version 1 & version 2 report file together in the morning when I am back on my work machine.

**Comment by WillGibson** [comment]
I've dropped you a couple of files in an email @cfryerdev.

**Comment by eliezercazares** [comment]
Guys are you planning to close this one? I need it badly

**Comment by cfryerdev** [comment]
Sorry, waiting on @hassy to close it, cant myself bud.

**Comment by cfryerdev** [comment]
Try it here: http://www.aioreportviewer.com/ until this is merged.

**Comment by eliezercazares** [comment]
> Try it here: http://www.aioreportviewer.com/ until this is merged.

Thanks a lot cfryerdev!
However it did not work for me, in Safari / macOS:
image

It might be that I am setting the extendedMetrics parameter?
`
config:
  extendedMetrics: true
`

**Comment by SantiagoGalicia** [comment]
hi team, when will be available this reporter?

**Comment by WillGibson** [comment]
I'm no longer working at the pace where this was relevant and it's been a while so I'm going to close this pull request to reduce noise.

**Pull request closed without merging**
